GET http://localhost:3005/

### Send fetch all songs request
GET http://localhost:3005/songs/

### Send fetch a song request
GET http://localhost:3005/songs/1

### Send create a song request
POST http://localhost:3005/songs/
Content-Type: application/json

{
   "title": "Animals",
  "artists": ["Martin Garrix"],
  "releaseDate": "2013-06-01",
  "duration": "02:15"
}

### Send update a song request
PUT http://localhost:3005/songs/1

### Send delete a song request
DELETE http://localhost:3005/songs/1
